spring.application.name=demo
spring.datasource.url=jdbc:mysql://10.0.0.1:3306/ddbb
spring.datasource.username=fila1
spring.datasource.password=chinchilla+123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true